### PR TITLE
SlackUpdate

### PR DESCRIPTION
**Pull request by Ant-Green**
peturgretars on slack noted the info messages about the test object where at the start of the invoke, moved to the end block to stop them showing unless you forget -PassThru

# A New PR

THANK YOU - We love to get PR's and really appreciate your time and help to improve this module

## Accepting a PR

Before we accept the PR - please confirm that you have run the tests locally to avoid our automated build and release process failing. You can see how to do that in our wiki

https://github.com/sqlcollaborative/dbachecks/wiki 

## Please confirm you have 0 failing Pester Tests

[] There are 0 failing Pester tests

## Changes this PR brings

Please add below the changes that this PR covers. It doesnt need an essay just the bullet points :-)

Convert-DbcResult was showing messages re -PassThru even if it had been switched on, moved code to end block to only capture if -PassThru wasn't passed

### CODE REVIEW

**Comment by Ant-Green** [comment]
Did I mess something up here, cant see why the build failed looking at the log?

**Comment by SQLDBAWithABeard** [comment]
[-] csv File should have the correct contents 120ms
        Expected '"Date","Label","Describe","Context","Name","Database","ComputerName","Instance","Result","FailureMessage"
        ".*","Testing","Last Good DBCC CHECKDB","Testing Last Good DBCC CHECKDB","Database master last good integrity check should be less than 3 days old","master","localhost,15592","localhost,15592","Failed","Expected the actual value to be greater than 2019-12-21T15:21:38.3892727Z, because You should have run a DBCC CheckDB inside that time, but got 2019-12-21T14:41:58.0230000."
        ".*","Testing","Last Good DBCC CHECKDB","Testing Last Good DBCC CHECKDB","Database master has Data Purity Enabled","master","localhost,15592","localhost,15592","Passed",""' to be found in file 'C:\Users\runneradmin\AppData\Local\Temp\e8fda3a0-96b8-4981-9e6d-6fdeaca02985\DummyFileName.csv', but it was not found.

**Comment by SQLDBAWithABeard** [comment]
Something similar with the XML file check

 to be found in file 'C:\Users\runneradmin\AppData\Local\Temp\e8fda3a0-96b8-4981-9e6d-6fdeaca02985\DummyFileName.xml', but it was not found.

**Comment by SQLDBAWithABeard** [comment]
It pains me to close this PR but I must as I cannot see how or why this change breaks the pester tests for set-dbcfile - but it does and it can only be in that one place int eh command. I know not why.

I am sorry

**Pull request closed without merging**
