### PR TITLE
so we can have new pwsh

### PR DESCRIPTION
**Pull request by jpomfret**
# A New PR

THANK YOU - We love to get PR's and really appreciate your time and help to improve this module

## Accepting a PR

Before we accept the PR - please confirm that you have run the tests locally to avoid our automated build and release process failing. You can see how to do that in our wiki

https://github.com/sqlcollaborative/dbachecks/wiki 

## Please confirm you have 0 failing Pester Tests

[] There are 0 failing Pester tests

## Changes this PR brings

Please add below the changes that this PR covers. It doesnt need an essay just the bullet points :-)

### CODE REVIEW

**Comment by jpomfret** [comment]
@SQLDBAWithABeard is recording a podcast so moo 🐱 approved...

**Comment by jpomfret** [comment]
hmmm used the old workflow file and not the new one 🤔

**Comment by SQLDBAWithABeard** [comment]
yarg

**Comment by SQLDBAWithABeard** [comment]
It was using the new workflow as it had the create PR on it but for some reason it could no longer tag the repo.

AS it turns out we dont need to tag the repo for containers so I #943 which should fix it.

**Comment by SQLDBAWithABeard** [comment]
It was using the new workflow as it had the create PR on it but for some reason it could no longer tag the repo.

AS it turns out we dont need to tag the repo for containers so I #943 whihc should fix it. Can you re- PR

**Comment by SQLDBAWithABeard** [comment]
because it wont pick up the new workflow for some reason

**Pull request closed without merging**
